services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn api.wsgi:application --chdir backend
    envVars:
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: django-backend.onrender.com,localhost,127.0.0.1
