# Generated by Django 5.2 on 2025-04-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0002_job_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AddField(
            model_name='job',
            name='Job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
