# Generated by Django 5.2 on 2025-04-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0003_alter_application_options_remove_job_id_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companylogo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='linkshare.company'),
        ),
    ]
