# Generated by Django 5.2 on 2025-04-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0005_remove_company_id_company_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Job_id',
        ),
        migrations.AddField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkshare.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
